services:
  app:
    build: .
    container_name: flask_app
    environment:
      # set database, memcached etc credentials
      DB_HOST: mysql
      DB_NAME: flask
      DB_USER: flask
      DB_PASSWORD: slimdingo85
    links:
      # network connection with these services
      - mysql
    depends_on:
      # build those images first
      - mysql
    ports:
      # bind on our 5000 port because most people have 80, 8080 already bound
      - "5000:5000"

  mysql:
    container_name: flask_mysql
    # let's grab from mysql 5.7 image
    image: mysql:latest
    volumes:
        # pass volume named mysql-data to mysql container
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    # ports:
    #   - "3310:3306"
    environment:
      # credentials
      MYSQL_ROOT_PASSWORD: slimdingo85
      MYSQL_DATABASE: flask
      MYSQL_USER: flask
      MYSQL_PASSWORD: slimdingo85

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    container_name: flask_phpmyadmin
    restart: unless-stopped
    ports:
      - "5010:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: flask
      PMA_PASSWORD: slimdingo85
      MYSQL_ROOT_PASSWORD: slimdingo85

# volumes definition here
volumes:
  # just a persistance data
  mysql-data:
    driver: local